### ISSUE TITLE
stoa0045.stoa002.perseus-lat2.xml breaking the text extraction

### ISSUE THREAD

**Issue by sonofmun** [PerseusDL/canonical-latinLit#226]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/bin/hooktest-build", line 11, in <module>
    sys.exit(cmd_build())
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/HookTest/cmd.py", line 130, in cmd_build
    status, message = HookTest.build.cmd(**vars(parse_args_build(sys.argv[1:])))
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/HookTest/build.py", line 163, in cmd
    txt=kwargs['txt'], cites=kwargs['cites']).run()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/HookTest/build.py", line 144, in run
    self.plain_text()
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/HookTest/build.py", line 112, in plain_text
    passages = [interactive_text.getTextualNode(passage) for passage in reffs]
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/HookTest/build.py", line 112, in <listcomp>
    passages = [interactive_text.getTextualNode(passage) for passage in reffs]
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/resources/texts/local/capitains/cts.py", line 88, in getTextualNode
    root = passageLoop(xml, root, start, end)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/common/utils.py", line 375, in passageLoop
    queue_2
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/common/utils.py", line 350, in passageLoop
    result_1, loop = performXpath(parent, current_1)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/MyCapytain/common/utils.py", line 253, in performXpath
    return result[0], loop
IndexError: list index out of range
```

**Comment by sonofmun** [comment]
I added a @type to the teiHeader to cause the file to fail so that it will not try to build and extract it. Once we figure out what the problem is, we can remove this.

**Comment by lcerrato** [comment]
@sonofmun 
I inadvertently added this my quick fix list in the last PR but just backed it out of there. I requested your review to make sure I didn't recreate the issue.
I can review this text in its own branch if you think it is something reparable on the text side but since the error occurs in the extraction process during the build I'm not sure my changes would fix it. And I probably wouldn't know it was flailing during the usual workflow.

**Comment by PonteIneptique** [comment]
I found the origin of the issue and fixed it : https://github.com/Capitains/MyCapytain/pull/138

Once it's merged, you should just rerun the Travis Test ;)

**Comment by sonofmun** [comment]
@PonteIneptique Inept Bridge to the rescue again!

**Comment by lcerrato** [comment]
@PonteIneptique @sonofmun Thanks!

**Comment by PonteIneptique** [comment]
I think we can close this one
