### ISSUE TITLE
Travis can't build

### ISSUE THREAD

**Issue by sonofmun** [PerseusDL/canonical-latinLit#243]
Errors when extracting plain text. The text in question is phi0119.phi012.perseus-eng2.xml. When I remove this text from the repo locally, the build works. The error is:

```
$ hooktest-build --travis --txt ./
Extracting Text.
...................multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/python/3.5.5/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/build.py", line 124, in build_texts
    passages = [interactive_text.getTextualNode(passage) for passage in reffs]
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/build.py", line 124, in <listcomp>
    passages = [interactive_text.getTextualNode(passage) for passage in reffs]
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/MyCapytain/resources/texts/local/capitains/cts.py", line 66, in getTextualNode
    start, end = subreference.start.list, subreference.start.list
AttributeError: 'NoneType' object has no attribute 'list'
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/bin/hooktest-build", line 11, in <module>
    sys.exit(cmd_build())
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/cmd.py", line 135, in cmd_build
    status, message = HookTest.build.cmd(**vars(parse_args_build(sys.argv[1:])))
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/build.py", line 175, in cmd
    txt=kwargs['txt'], cites=kwargs['cites'], workers=int(kwargs['workers'])).run()
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/build.py", line 156, in run
    self.plain_text()
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/HookTest/build.py", line 113, in plain_text
    for _ in executor.imap_unordered(self.build_texts, [text for text in passing_texts]):
  File "/opt/python/3.5.5/lib/python3.5/multiprocessing/pool.py", line 731, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'list'
```

**Comment by sonofmun** [comment]
Fixed in PR #244
